greeting:
  message: "hello"

quarkus:
  native:
    additional-build-args: -H:IncludeResources=fj-doc-native-quarkus/fm-doc-process-config.xml,\
      -H:IncludeResources=fj-doc-native-quarkus/template/document.ftl