[#doc-useful-resources]
=== Useful resources

This section contains some useful resources.

==== Online playground

The online playground where you can try Fugerit Venus Doc features :

link:include::chapters/https://docs.fugerit.org/fj-doc-playground/home/[https://docs.fugerit.org/fj-doc-playground/home/]

[#doc-res-link-sample-index]
==== Venus Fugerit Doc sample index

The link:https://github.com/fugerit79/venus-sample-index[Venus Fugerit Doc sample index] contains an index of some sample tutorials on specific features.

[#doc-res-link-mongo-ds]
==== Mongo DB JSON Data Source Example

The link:https://github.com/fugerit79/venus-sample-mongodb-ds[Venus Fugerit Doc sample using a MongoDB data source] is a simple project showing how is possible to load the data model from a Mongo DB Collection and setting it directly as JSON.

[#doc-res-link-extend-type-handler]
==== Extending a Type Handler with custom behaviours

The link:https://github.com/fugerit79/venus-sample-custom-fop-type-handler[Venus Fugerit Doc Sample project implementing a Custom Apache FOP type handler] shows how is it possible to customize doc handlers behaviors.

[#doc-res-link-validate-source]
==== Validating an XML source

The link:https://github.com/fugerit79/venus-sample-validating-source[Venus Fugerit Doc sample showing how to validate source documents] to debug unexpected behaviors.

[#doc-res-link-clean-source]
==== Cleaning an XML source

The link:https://github.com/fugerit79/venus-sample-clean-source[Venus Fugerit Doc sample showing ability to clean source XML] this can be useful when facing error like _An invalid XML character (Unicode: 0x2) was found in the element content of the document_.

[#doc-res-link-pdf-fop-accessibility]
==== PDF/UA-1 accessibility for PDF

The link:https://github.com/fugerit79/venus-sample-pdf-fop-accessibility[Venus Fugerit Doc sample showing how to use accessibility features of PDF FOP type handler], additionally contains info on PDF/A format support and output file size comparison.