[#doc-format-entry-point-extra-features]
=== Doc Format Extra Features

Some extra features are available on the Venus Doc Format. Here is a listing.

[#doc-format-entry-point-extra-feature-table-check-integrity]
==== Table Check Integrity

Sometimes using table with wrong number of columns and rows anc lead to unexpected behaviour or errors.

Using the doc info 'table-check-integrity' can solve this issue, for instance :

[source,xml]
----
<info name="table-check-integrity">fail</info>
----

link:https://venusdocs.fugerit.org/docs/html/doc_meta_info.html#table-check-integrity[Here is  'table-check-integrity' documentation].

Accepted values are :

* 'disabled' - no check (default value)
* 'warn' - check table integrity and print warning on log
* 'fail' - as warn but raises a DocFeatureRuntimeException

Here is an example of a table where there is an extra column on the second row.

[source,xml]
----
<table columns="3" colwidths="30;30;40"  width="100" id="data-table" padding="2">
    <row header="true">
        <cell align="center"><para>Name</para></cell>
        <cell align="center"><para>Surname</para></cell>
        <cell align="center"><para>Title</para></cell>
    </row>
    <row>
        <cell><para>Queen</para></cell>
        <cell><para>Luthien</para></cell>
        <cell><para>Tinuviel</para></cell>
        <cell><para>Extra column (Row 1 has 4 columns instead of 3)</para></cell>
    </row>
    <row>
        <cell><para>King</para></cell>
        <cell><para>Thorin</para></cell>
        <cell><para>Oakshield</para></cell>
    </row>
</table>
----

When using xref:#doc-freemarker-config[FreemarkerDocProcessConfig]
it is also possible to set a global configuration on
link:https://venusdocs.fugerit.org/fj-doc-freemarker/src/main/docs/fdp_xsd_config_ref.html#freemarker-doc-process-config[freemarker-doc-process-config] :

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<freemarker-doc-process-config
	xmlns="https://freemarkerdocprocess.fugerit.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://freemarkerdocprocess.fugerit.org https://www.fugerit.org/data/java/doc/xsd/freemarker-doc-process-1-0.xsd"
	table-check-integrity="warn">
    <!-- ... further configuration ... -->
</freemarker-doc-process-config>
----

Priority order is :

* document level configuration (info tag)
* global configuration (taken into account only if info tag not set)
