#Sample native helper config file
---
generate:
  - packageName: org.fugerit.java.doc.base.model
    mode: all
    typeReachable: org.fugerit.java.doc.base.facade.DocFacadeSource
  - packageName: org.fugerit.java.doc.base.config
    mode: all
    typeReachable: org.fugerit.java.doc.base.facade.DocFacadeSource
  - packageName: org.fugerit.java.doc.base.parser
    mode: all
    typeReachable: org.fugerit.java.doc.base.facade.DocFacadeSource
  - packageName: org.fugerit.java.doc.base.xml
    mode: all
    typeReachable: org.fugerit.java.doc.base.facade.DocFacadeSource
  - packageName: org.fugerit.java.doc.base.typehandler.markdown
    mode: all
    typeReachable: org.fugerit.java.doc.base.facade.DocFacadeSource
  - packageName: org.fugerit.java.doc.base.typehandler.core
    mode: all
    typeReachable: org.fugerit.java.doc.base.facade.DocFacadeSource
  - className: org.fugerit.java.doc.base.model.util.DocTableUtil
    mode: all
    typeReachable: org.fugerit.java.doc.base.facade.DocFacadeSource