<?xml version="1.0" encoding="UTF-8" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>${context.groupId}</groupId>
    <artifactId>${context.artifactId}</artifactId>
    <version>${context.projectVersion}</version>
    <packaging>war</packaging>

    <properties>
        <maven.compiler.source>${context.javaRelease}</maven.compiler.source>
        <maven.compiler.target>${context.javaRelease}</maven.compiler.target>
        <maven.compiler.release>${context.javaRelease}</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <openliberty-runtime-version>24.0.0.9</openliberty-runtime-version>
        <liberty-maven-plugin-version>3.10.3</liberty-maven-plugin-version>
        <microprofile-version>6.1</microprofile-version>
        <liberty.var.default.http.port>8080</liberty.var.default.http.port>
        <liberty.var.default.https.port>8443</liberty.var.default.https.port>
        <junit-bom-version>5.11.0</junit-bom-version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${r"${junit-bom-version}"}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.openliberty</groupId>
            <artifactId>openliberty-runtime</artifactId>
            <version>${r"${openliberty-runtime-version}"}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>org.eclipse.microprofile</groupId>
            <artifactId>microprofile</artifactId>
            <version>${r"${microprofile-version}"}</version>
            <type>pom</type>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>fugerit-openliberty-template</finalName>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>io.openliberty.tools</groupId>
                    <artifactId>liberty-maven-plugin</artifactId>
                    <version>${r"${liberty-maven-plugin-version}"}</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>io.openliberty.tools</groupId>
                <artifactId>liberty-maven-plugin</artifactId>
                <configuration>
                    <serverName>libertyServer</serverName>
                    <runtimeArtifact>
                        <groupId>io.openliberty</groupId>
                        <artifactId>openliberty-runtime</artifactId>
                        <version>${r"${openliberty-runtime-version}"}</version>
                        <type>zip</type>
                    </runtimeArtifact>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
